config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :answers
    resources :notes
    resources :prayers
    resources :statuses
    resources :types
    resources :topics
    resources :tags
    resources :roles
    devise_for :users
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines the root path route ("/")
    root "home#index"
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :prayer

  validates :prayer, :content, presence: true

  after_save :update_prayer_answers_count
  after_destroy :update_prayer_answers_count

  def update_prayer_answers_count
    prayer.update(answers_count: prayer.answers.count)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :prayer
  belongs_to :user

  validates :content, :prayer, :title, presence: true

  after_save :update_prayer_notes_count
  after_destroy :update_prayer_notes_count

  def update_prayer_notes_count
    prayer.update(notes_count: prayer.notes.count)
  end
end

app/models/prayer.rb
class Prayer < ApplicationRecord
  belongs_to :status
  belongs_to :type
  belongs_to :user

  has_many :notes, dependent: :destroy
  has_many :answers, dependent: :destroy

  has_and_belongs_to_many :tags

  attribute :datetime_to_pray, default: -> { Time.current }

  validates :description, :status, :type, :user, :location, :summary, presence: true
  validates :datetime_to_pray, presence: true, timeliness: { type: :date }
  validates_length_of :words_in_summary, within: 2..8
  validates :notes_count, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :answers_count, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :priority, inclusion: { in: PriorityLevels::LEVELS }

  private

  def words_in_summary
    return '' if summary.blank?

    summary.scan(/\w+/)
  end
end

app/models/role.rb
class Role < ApplicationRecord
  validates :title, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  validates :title, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :topics, dependent: :destroy
  has_many :types, dependent: :destroy

  has_and_belongs_to_many :prayers

  validates :label, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :tag

  has_many :types, dependent: :destroy

  validates :title, :description, :tag, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :topic
  belongs_to :tag, required: false

  validates :label, :subject, :description, :topic, presence: true
  validates :prayer_duration, numericality: { only_integer: true, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [24, 24]
    attachable.variant :small, resize_to_limit: [48, 48]
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role

  validates :email, :username, :role, presence: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: %i[show edit update destroy]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show; end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit; end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy!

    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def note_params
    params.require(:note).permit(:prayer_id, :title, :content, :user_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: %i[show edit update destroy]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show; end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit; end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy!

    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:label, :bg_color, :color)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_date(date)
    current_year = Date.today.year

    formatted_date = date.strftime('%d %b')
    formatted_date += " #{date.year}" if date.year != current_year

    formatted_date
  end

  def avatar_text(name)
    name[0].upcase
  end

  def get_or_default(size, default)
    size || default
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/prayers_helper.rb
module PrayersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note, class: "contents") do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>
      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :prayer_id %>
    <%= form.text_field :prayer_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :content %>
    <%= form.text_field :content, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <div class="chat <%= note.user == current_user ? "chat-end" : "chat-start" %>">
    <div class="chat-image">
      <%= render partial: "shared/avatar", locals: { user: note.user, size: 3, img_variant: :small } %>
    </div>
    <div class="chat-bubble text-gray-500 bg-gray-100 w-full">
      <div class="flex justify-between items-center w-full">
        <h3 class="font-semibold text-black">
          <%= note.title %>
        </h3>
        <span class="material-symbols-outlined small-icon">
          description
        </span>
      </div>
      <p class="chat-content text-sm w-full">
        <%= note.content %>
      </p>
    </div>
    <div class="chat-footer flex items-center justify-between pr-4 pl-4 w-full max-w-[90%]">
      <time class="text-gray-400 text-sm" datetime="<%= note.created_at %>" data-controller="timeago"></time>
      <div class="flex flex-row">
        <% if note.user == current_user %>
          <button class="btn btn-transparent text-gray-500 font-normal min-h-8 h-8 pl-2 pr-2">
            <span class="material-symbols-outlined small-icon">
              edit
            </span>
            <p class="text-sm">Edit</p>
          </button>
          <button class="btn btn-transparent text-gray-500 font-normal min-h-8 h-8 pl-2 pr-2">
            <span class="material-symbols-outlined small-icon">
              delete
            </span>
            <p class="text-sm">Remove</p>
          </button>
        <% else %>
          <button class="btn btn-transparent text-gray-500 font-normal min-h-8 h-8 pl-2 pr-2">
            <span class="material-symbols-outlined small-icon">
              quickreply
            </span>
            <p class="text-sm">Private reply</p>
          </button>
          <button class="btn btn-transparent text-gray-500 font-normal min-h-8 h-8 pl-2 pr-2">
            <span class="material-symbols-outlined small-icon">
              reply
            </span>
            <p class="text-sm">Reply</p>
          </button>
        <% end%>
      </div>
    </div>
  </div>
</div>

app/views/notes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing note</h1>

  <%= render "form", note: @note %>

  <%= link_to "Show this note", @note, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to notes", notes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/notes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Notes</h1>
    <%= link_to "New note", new_note_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="notes" class="min-w-full">
    <%= render @notes %>
  </div>
</div>

app/views/notes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New note</h1>

  <%= render "form", note: @note %>

  <%= link_to "Back to notes", notes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/notes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @note %>

    <%= link_to "Edit this note", edit_note_path(@note), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this note", note_path(@note), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to notes", notes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/tags/_form.html.erb
<%= form_with(model: tag, class: "contents") do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>
      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :label %>
    <%= form.text_field :label, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :bg_color %>
    <%= form.text_field :bg_color, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :color %>
    <%= form.text_field :color, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <span class="badge p-4 text-base rounded-lg font-semibold" style="background-color: <%= tag.bg_color %>; color: <%= tag.color %>"><%= tag.label.capitalize %></span>
</div>

app/views/tags/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing tag</h1>

  <%= render "form", tag: @tag %>

  <%= link_to "Show this tag", @tag, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to tags", tags_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tags/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tags</h1>
    <%= link_to "New tag", new_tag_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="tags" class="min-w-full">
    <%= render @tags %>
  </div>
</div>

app/views/tags/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New tag</h1>

  <%= render "form", tag: @tag %>

  <%= link_to "Back to tags", tags_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tags/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @tag %>

    <%= link_to "Edit this tag", edit_tag_path(@tag), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this tag", tag_path(@tag), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to tags", tags_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>