config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :answers
    resources :notes
    resources :prayers
    resources :statuses
    resources :types
    resources :topics
    resources :tags
    resources :roles
    devise_for :users
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines the root path route ("/")
    root "home#index"
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :prayer

  validates :prayer, :content, presence: true

  after_save :update_prayer_answers_count
  after_destroy :update_prayer_answers_count

  def update_prayer_answers_count
    prayer.update(answers_count: prayer.answers.count)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :prayer
  belongs_to :user

  validates :content, :prayer, :title, presence: true

  after_save :update_prayer_notes_count
  after_destroy :update_prayer_notes_count

  def update_prayer_notes_count
    prayer.update(notes_count: prayer.notes.count)
  end
end

app/models/prayer.rb
class Prayer < ApplicationRecord
  belongs_to :status
  belongs_to :type
  belongs_to :user

  has_many :notes, dependent: :destroy
  has_many :answers, dependent: :destroy

  has_and_belongs_to_many :tags

  attribute :datetime_to_pray, default: -> { Time.current }

  validates :description, :status, :type, :user, :location, :summary, presence: true
  validates :datetime_to_pray, presence: true, timeliness: { type: :date }
  validates_length_of :words_in_summary, within: 2..8
  validates :notes_count, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :answers_count, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :priority, inclusion: { in: PriorityLevels::LEVELS }

  private

  def words_in_summary
    return '' if summary.blank?

    summary.scan(/\w+/)
  end
end

app/models/role.rb
class Role < ApplicationRecord
  validates :title, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  validates :title, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :topics, dependent: :destroy
  has_many :types, dependent: :destroy

  has_and_belongs_to_many :prayers

  validates :label, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :tag

  has_many :types, dependent: :destroy

  validates :title, :description, :tag, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
  belongs_to :topic
  belongs_to :tag, required: false

  validates :label, :subject, :description, :topic, presence: true
  validates :prayer_duration, numericality: { only_integer: true, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [24, 24]
    attachable.variant :small, resize_to_limit: [48, 48]
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role

  validates :email, :username, :role, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[show edit update destroy]

  # GET /answers or /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1 or /answers/1.json
  def show; end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit; end

  # POST /answers or /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to answer_url(@answer), notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to answer_url(@answer), notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @answer.destroy!

    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def answer_params
    params.require(:answer).permit(:prayer_id, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: %i[show edit update destroy]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show; end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit; end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy!

    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:label, :bg_color, :color)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_date(date)
    current_year = Date.today.year

    formatted_date = date.strftime('%d %b')
    formatted_date += " #{date.year}" if date.year != current_year

    formatted_date
  end

  def avatar_text(name)
    name[0].upcase
  end

  def get_or_default(size, default)
    size || default
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/prayers_helper.rb
module PrayersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/answers/_answer.html.erb
<div id="<%= dom_id answer %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Prayer:</strong>
    <%= answer.prayer_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= answer.content %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this answer", answer, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this answer", edit_answer_path(answer), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/answers/_form.html.erb
<%= form_with(model: answer, class: "contents") do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :prayer_id %>
    <%= form.text_field :prayer_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.text_field :content, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing answer</h1>

  <%= render "form", answer: @answer %>

  <%= link_to "Show this answer", @answer, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to answers", answers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/answers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Answers</h1>
    <%= link_to "New answer", new_answer_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="answers" class="min-w-full">
    <%= render @answers %>
  </div>
</div>

app/views/answers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New answer</h1>

  <%= render "form", answer: @answer %>

  <%= link_to "Back to answers", answers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/answers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @answer %>

    <%= link_to "Edit this answer", edit_answer_path(@answer), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this answer", answer_path(@answer), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to answers", answers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>